### ISSUE TITLE
In Android 14 not compatible

### ISSUE THREAD

**Issue by jyotirajwaniya91** [ElectApp/MyMQTT#1]
Hello,
Can u please update the solution for Android 14, as it is not working into it.

Thanks

**Comment by ElectApp** [comment]
Hello,
I just tested it on Android 14 and found it to work fine. In the case of connecting to a broker with a password You must modify the code by specifying options. 
`MqttConnectOptions options = new MqttConnectOptions();`
`options.setUserName(MQTT_USERNAME);`
`options.setPassword(MQTT_PASSWORD.toCharArray());`

You can see an example from here.
[https://github.com/ElectApp/MyMQTT/blob/3446c5876a60c8fdb3d9d4ff64a78ee390713dd5/app/src/main/java/com/somsakelect/android/mymqtt/MainActivity.java#L117](url)

Thanks

**Comment by ElectApp** [comment]
@jyotirajwaniya91 I just update example code for android 12+. Please check at AndroidManifest.xml and MainActivity.java. 

The error that you found on android 14 like picture below. 
![Android14_MQTT_ERROR_with_SCHEDULE_EXACT_ALARM](https://github.com/ElectApp/MyMQTT/assets/37909428/c84cd2ed-081a-4002-80cc-c97bd59a114d)

This is explained from google.
[https://developer.android.com/about/versions/14/changes/schedule-exact-alarms](url)
